name: Build and Release

on:
  # option to run manually from the Actions tab
  workflow_dispatch:

  # can be called from other workflows
  workflow_call:

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --only=production --ignore-scripts

      - name: Build lib
        run: npm run build

      - name: Publish lib
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
