name: Generate Visual Test Snapshot

on:
  # option to run manually from the Actions tab
  workflow_dispatch:

  # can be called from other workflows
  workflow_call:

jobs:
  snapshot:
    name: Generate Visual Test Snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Setting up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-chromedriver: true

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.1'

      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build project
        run: npm run build

      - name: Install Browser
        run: npx puppeteer browsers install chrome

      - name: Test
        run: npm run test -- --coverage --updateSnapshot
        env:
          CI: true

      - name: Upload visual test diffs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-test-report
          path: |
            src/**/__image_snapshots__/*.png
            src/**/__image_snapshots__/**/*.png
