name: Package lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    name: Linting and Testing
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.1'

      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build project
        run: npm run build

      - name: ESLint
        run: npm run lint:check

      - name: Code format check
        run: npm run format:check
